# Generated by Django 5.1.3 on 2024-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructors_delete_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the banner', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Upload a banner image', upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
